# Generated by Django 5.0.7 on 2025-02-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progresstracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizprogress',
            name='topic',
            field=models.CharField(max_length=255),
        ),
    ]
